name = "SHA2"
uuid = "9d4ddf4f-6d06-4582-acde-b0648dc3c616"
authors = ["Erich Neun <erich-9@gmx.de> and contributors"]
version = "0.0.1"

[deps]

[compat]
Aqua = "0.8"
SHA = "<0.0.1, 0.7, 1"
Test = "<0.0.1, 1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "SHA", "Test"]
